### ISSUE TITLE
Refactor names and keys of indicators

### ISSUE THREAD

**Issue by mmaelicke** [sumo-rhine/kinamo#14]
I would suggest a minor refactoring of the indicator model. Right now sub-indicator keys have underscores:

https://github.com/sumo-rhine/kinamo/blob/2ae535a9e58bc19a918bebab5b361dfdd26386b2/sample_data.json#L38

First, it is common practice in javascript to use camelCase. Main reason:

```javascript
indicator.carFreeArea     # possible
indicator.car_free_area   # not possible
```

Secondly, we should have a short name and a long name or full name for each one. Think of a table with all indicator names:

https://github.com/sumo-rhine/kinamo/blob/2ae535a9e58bc19a918bebab5b361dfdd26386b2/sample_data.json#L46

this does not really make a good column header. But camelCase or under_score names are aslo ugly.

Thus my suggestion:

1. use camelCase for the key in the object
2. use `shortName` or `name` for headings (i.e. `Facilities`) 
3. use `fullName`  for the full name (i.e. `Density of Cafés, Restaurants, Bars, Convenience Store, Grocery Store, Playground`)

@JesJehle What do you think?

**Comment by JesJehle** [comment]
I am OK with all the propositions. The names will be shortened!
