### ISSUE TITLE
City Card Component

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#25]
A component displaying the city as a card for the carousel component.
![image](https://user-images.githubusercontent.com/23353378/118240469-57267200-b49b-11eb-8543-84b07fa3e925.png)

**Comment by mmaelicke** [comment]
Is this only for the front page carousel or could this be reused on the product-comparison page, before the header collapsed?

**Comment by mmaelicke** [comment]
Few more minor questions:

Does the card have a fixed two-column layout that holds on mobile devices, or should it be responsive?

The data on the card originates from the dataset: `city.name`, `city.description`, right?

What about the image? Static content on the application itself, or should it be added to firebase? For the latter we need to extent the city datamodel to hold a `src` for the thumbnail. 
Static image is more straightforward but can have a performance impact, firebase is faster and more flexible, but needs more implementation work.
