### ISSUE TITLE
switch from ant design to material-ui

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#28]
- [ ] install material ui 
- [ ] import

**Comment by mmaelicke** [comment]
- [ ] replace ant design components with material ui components
- [ ] check most fundamental building blocks for pages in material ui

The last point is ie. important to specify if we want one Header component that always looks the same, or if each major Page defines its own Header. The same applies to footer components, Main menu etc.

**Comment by mmaelicke** [comment]
This is done right?
