### ISSUE TITLE
Cannot rotate HERE Map

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#31]
I struggle to create the map rotation animation in the MapBanner component.

The [documentation](https://developer.here.com/documentation/maps/3.1.5.0/dev_guide/topics_api/h-map-viewmodel.html) proposes using the control method of the H.map.ViewModel, but I cannot get it to work.

I already implemented:
```
   const view = hMap.getViewModel();
    view.setLookAtData({
      tilt: 70,
    });
    // const moveX
    // const moveY
    // const moveZ
    // const rotateX
    // const rotateY
    // const rotateZ

    view.startControl(true);
    // view.control({ rotateX: 3 });
    view.endControl(true);
```
`view.control({ rotateX: 3 });` give an error and I don't know how to pass the argument properly
Maybe you have an idea?

**Comment by mmaelicke** [comment]
I'll have a look

**Comment by JesJehle** [comment]
Since, I use css animation. We don't need this any more.
