### ISSUE TITLE
Migrate redux to redux-toolkit

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#32]
Is there any reason for you not to use redux-toolkit?. It seems a lot simpler to me.

**Comment by mmaelicke** [comment]
No reason. I wanted to keep the dependency list as short as possible  for the start. In terms of learning ist good to get to know redux first, nur If you feel comfortable with Toolkit, Go dir that. I think ist is build by the Same Guys, so should integrate nicely

**Comment by JesJehle** [comment]
Lets keep it simple and stick to redux.
