### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by mmaelicke** [sumo-rhine/kinamo#4]
@JesJehle 
Wollen/Dürfen/Können wir Google Analytics einbinden? 
Ich wäre sehr dafür da wir später kaum effektiv bottlenecks identifizieren und beheben können.

Wenn ja, wie? (anonymized IP, oder user auseinanderhalten können)
- Nutzungsstatistiken?
- Performance? 
- A/B testing?

**Comment by JesJehle** [comment]
Ja, würde ich gerne integrieren, auch um das Nutzerverhalten auf der Webseite besser verstehen und auswerten zu können. Ich würde Erste einmal so viele Daten nehmen, wie wir bekommen können. Wir können uns darüber auch gerne nächstes Mal austauschen.
A/B testing fänd ich super interessant, weiß aber nicht wie realistisch das in diesem Projekt ist. Wir sollten uns aber erst mal alles offen halten!

**Comment by mmaelicke** [comment]
Gut dann bau ich es erstmal mit ein. Solange die Seite nicht live ist, ist das auch kein Problem. 
Wichtig hierbei ist: Sobald die Seite live ist, muss es eine Datenschutzerklärung und ein Impressum geben. 

In die Datenschutzerklärung muss Google Analytics mit rein, und der Nutzer braucht eine Möglichkeit das auszuschalten. Für das Impressum ist wichtig, dass die Seite momentan die hydrocode GbR betreibt. Das muss dann ggf. angepasst werden, wenn ihr die Kontrolle übernehmt.
