### ISSUE TITLE
New Main Table Component

### ISSUE THREAD

**Issue by mmaelicke** [sumo-rhine/kinamo#40]
After #38 finished, build a component to display the new main table. 

- [x] Import and use default material data table
- [x] Load the data and transform into display format

**Comment by mmaelicke** [comment]
@JesJehle implementing the data grid is quite challenging for our data model. The names of the indicators are too long, it does not even fit on my 1900px screen. Also, Kinamo is using material-ui version 4, although 5 is already out. Is there a special reason to stick to 4?
I am asking because they look a bit different.

Which functionality of the data-grid do we need?

**Comment by JesJehle** [comment]
No, let's update material-ui.
We only need sorting. I can try to make the indicator names even shorter. Next to this, we can implement scrolling or pegination

**Comment by JesJehle** [comment]
@mmaelicke I think we are strongly out of sync. On your last visit, we already converted all js files to ts, I unfortunately just pushed the chances this morning :) Is in the main branch ...
