### ISSUE TITLE
First Implementation of Bar Chart on City Page

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#62]
I would like to make a stacked Barchart. Each bar is one indicator, and the rank of the key figures sum up the bar.
The problem is, that there are no homogenous classes which make up the bars, but the key figures are different for each indicator, translating into different classes for each bar.
I don't know how to implement this with the standard plotting libraries.
What I need, is the possibility, to use custom values for each stacked bar chart according to the corresponding indicator and refigure values.
Do you have a good starting point for me, library or example?

**Comment by mmaelicke** [comment]
I am not sure if I got it. Do you have an example, or maybe short phone call?

**Comment by JesJehle** [comment]
Google Meet?
