### ISSUE TITLE
Assignees:@mmaelicke
Labels:

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#65]
Another ST Error, I have no idea why TS things its a string in the first place.

https://github.com/sumo-rhine/kinamo/blob/a393aafed4b5bca739f9e35b0e91e9b2d26518af/src/components/Carousel/Carousel-Item.tsx#L84-L84

TypeScript error in /home/jesjehle/projects/kinamo/src/components/Carousel/Carousel-Item.tsx(84,15):
Type 'string | undefined' is not assignable to type 'number | undefined'.
Type 'string' is not assignable to type 'number | undefined'. TS2322

    82 |           <Box pt={4} style={{ width: 400 }}>
    83 |             <KeyFigureBar
> 84 | points={data?.keyFigurePoints!.toFixed(1)}
       |               ^
    85 |             ></KeyFigureBar>
    86 |           </Box>
    87 |           <Box pt={4}>

**Comment by JesJehle** [comment]
Its all in the main branch.

**Comment by mmaelicke** [comment]
the javascript function `toFixed` has return type `string`. Pass the number as is and use `toFixed` on display. If you need to force a rounding on the `Number` type use the `Math.round` method.

**Comment by JesJehle** [comment]
The problem I have is, that some probs end up as undefined.
In `CarouselItem` I pass props as `CarouselItemProps`, they have `KeyFigurePoints` which filtered from the city data. This works and I can console log the data.
Now, the moment I try to pass the same data to the `KeyFigureBar` component via props. I get an Error:
```
TypeScript error in /home/jesjehle/projects/kinamo/src/components/Carousel/Carousel-Item.tsx(85,15):
Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.  TS2322

    83 |             <KeyFigureBar
    84 |               //TODO #65
  > 85 |               points={data?.keyFigurePoints}
       |               ^
    86 |             ></KeyFigureBar>
    87 |           </Box>
    88 |           <Box pt={4}>
```
I don't understand why and cannot resolve the issue.
I passed the state, so you should see the same error on the main branch

**Comment by mmaelicke** [comment]
I'll have a look

**Comment by mmaelicke** [comment]
The problem is that `data`can be undefined and when setting the state it is in fact undefined, because you build it this way. Therefore you cannot pass the property down as the object itself might not be defined. 
A quick fix for that, is to check if data is set and if not, never return the Carousel Item:

```typescript
  if (!data) {
    return (<p>404</p>)
  }
```

In perspective, we should build a 404 page and instead of returning something, navigate to that page. (Same for CityPage requests that cannot be resolved).
I just commited the fix.

**Comment by JesJehle** [comment]
Great, Thanks!

**Comment by JesJehle** [comment]
Do you have time for a short chat?

**Comment by JesJehle** [comment]
I still cannot access `keyFigurePoints`. At the same time, I can access `keyFigureUnit` and `keyFigureValue`.
